name: Workflow

on:
  push:
    branches:
    - master

jobs:
  pypi-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install twine
        run: pip install twine
      - name: Build package
        run: python setup.py sdist
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
